version: '3'

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: virtual_credit_development
      TZ: Asia/Tokyo
    ports:
      - '3307:3306'
    volumes:
      - ./tmp/db:/var/lib/mysql
    networks:
      - virtual_credit_common_network

  db_test:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: virtual_credit_test
      TZ: Asia/Tokyo
    ports:
      - '3308:3306'
    volumes:
      - ./tmp/db_test:/var/lib/mysql
    networks:
      - virtual_credit_common_network

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/virtual_credit_api
    ports:
      - '4000:4000'
    depends_on:
      - db
      - db_test
    networks:
      - virtual_credit_common_network

  doc:
    image: swaggerapi/swagger-ui
    volumes:
      - ./doc/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
    ports:
      - 8080:8080

networks:
  virtual_credit_common_network:
    external: true
