version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

# setup
commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: 'yarn.lock'

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.5-node-browsers
    steps:
      - setup
  spec:
    docker:
      - image: circleci/ruby:2.7.5-node-browsers
      - image: circleci/mysql:5.7
        name: db_test
        environment:
          MYSQL_USER: 'test'
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_PASSWORD: 'password'
          MYSQL_DATABASE: 'virtual_credit_test'
          MYSQL_HOST: 'db_test'
    environment:
      BUNDLE_JOBS: '4'
      BUNDLE_RETRY: '3'
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: ''
      RAILS_ENV: test
    steps:
      - setup
      - run:
          name: Database Migration
          command: bundle exec rake ridge:migrate
      - run:
          name: Run Rspec
          command: bundle exec rspec
  rubocop:
    docker:
      - image: circleci/ruby:2.7.5-node-browsers
    steps:
      - setup
      - run:
          name: rubocop
          command: bundle exec rubocop

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - spec:
          requires:
            - build
      - rubocop:
          requires:
            - build
