openapi: 3.0.2
info:
  title: VirtualCreditOpenAPI
  version: 1.0.0
  description: VirtualCreditSchemaInformation
  contact:
    name: email
    email: yukke5222@gmail.com
tags:
  - name: jobs
paths:
  /jobs:
    get:
      summary: ジョブ一覧を取得
      tags:
        - jobs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
      operationId: getJobs
      description: ジョブ一覧を取得
servers:
  - url: 'http://localhost:3000/api/v1'
    description: ローカル環境/v1
components:
  securitySchemes: {}
  schemas:
    Job:
      title: Job
      type: object
      description: ジョブ情報
      properties:
        id:
          type: integer
        name:
          type: string
        ancestry:
          type: string
          nullable: true
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
          nullable: true
      required:
        - id
        - name
        - ancestry
        - created_at
        - updated_at
        - deleted_at
  parameters: {}
  examples: {}
