openapi: 3.0.2
info:
  title: VirtualCreditOpenAPI
  version: 1.0.0
  description: VirtualCreditSchemaInformation
  contact:
    name: email
    email: yukke5222@gmail.com
tags:
  - name: Job
  - name: Category
  - name: Work
paths:
  /jobs:
    get:
      summary: ジョブ一覧
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
      operationId: getJobs
      description: ジョブ一覧を取得
      tags:
        - Job
    post:
      summary: ジョブ作成
      operationId: postJob
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
      description: ジョブを作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                ancestry:
                  type: string
                  nullable: true
              required:
                - name
                - ancestry
        description: ''
      tags:
        - Job
    parameters: []
  '/jobs/{job_id}':
    get:
      summary: ジョブ取得
      operationId: getJob
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      description: ジョブを取得
      tags:
        - Job
    patch:
      summary: ジョブ更新
      operationId: patchJob
      responses:
        '204':
          description: No Content
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
      description: ジョブを更新
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      tags:
        - Job
    parameters:
      - schema:
          type: integer
        name: job_id
        in: path
        required: true
    delete:
      summary: ジョブ削除
      operationId: deleteJob
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
      description: ジョブを削除
      tags:
        - Job
  /categories:
    get:
      summary: カテゴリ一覧
      tags:
        - Category
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
      operationId: getCategories
      description: カテゴリ一覧を取得
    post:
      summary: カテゴリ作成
      operationId: postCategory
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
      description: カテゴリを作成
      tags:
        - Category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                ancestry:
                  type: string
                  nullable: true
              required:
                - name
                - ancestry
  '/categories/{category_id}':
    parameters:
      - schema:
          type: integer
        name: category_id
        in: path
        required: true
    get:
      summary: カテゴリ取得
      tags:
        - Category
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
      operationId: getCategory
      description: カテゴリを取得
    patch:
      summary: カテゴリ更新
      operationId: patchCategory
      responses:
        '204':
          description: No Content
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
      description: カテゴリを更新
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      tags:
        - Category
    delete:
      summary: カテゴリ削除
      operationId: deleteCategory
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
      description: カテゴリを削除
      tags:
        - Category
  /works:
    get:
      summary: 作品一覧
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Work'
      operationId: getWorks
      description: 作品一覧を取得
      tags:
        - Work
    parameters: []
servers:
  - url: 'http://localhost:4000/api/v1'
    description: ローカル環境/v1
components:
  securitySchemes: {}
  schemas:
    Job:
      title: Job
      type: object
      description: ジョブ情報
      properties:
        id:
          type: integer
        name:
          type: string
        ancestry:
          type: string
          nullable: true
        number_of_users:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
          nullable: true
      required:
        - id
        - name
        - ancestry
        - number_of_users
        - created_at
        - updated_at
        - deleted_at
    Category:
      title: Category
      type: object
      description: カテゴリ情報
      properties:
        id:
          type: integer
        name:
          type: string
        ancestry:
          type: string
          nullable: true
        number_of_works:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
          nullable: true
      required:
        - id
        - name
        - ancestry
        - number_of_works
        - created_at
        - updated_at
        - deleted_at
    Work:
      title: Work
      type: object
      description: 作品情報
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        image_files:
          type: array
          items:
            $ref: '#/components/schemas/ImageFile'
        number_of_favorites:
          type: integer
        author:
          $ref: '#/components/schemas/Author'
        creators:
          type: array
          items:
            $ref: '#/components/schemas/Creator'
        category:
          $ref: '#/components/schemas/Category'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        assets:
          type: array
          items:
            $ref: '#/components/schemas/Asset'
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
          nullable: true
      required:
        - id
        - name
        - description
        - image_files
        - number_of_favorites
        - author
        - creators
        - category
        - created_at
        - updated_at
        - deleted_at
    ImageFile:
      title: ImageFile
      type: object
      description: 作品イメージ情報
      properties:
        id:
          type: integer
        sequence:
          type: integer
        file_type:
          type: integer
        image_url:
          type: string
        video_id:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
      required:
        - id
        - sequence
        - file_type
        - created_at
        - updated_at
        - deleted_at
    Tag:
      title: Tag
      type: object
      description: 作品タグ情報
      properties:
        id:
          type: integer
        name:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
      required:
        - id
        - name
        - author
        - created_at
        - updated_at
        - deleted_at
    Asset:
      title: Asset
      type: object
      description: 作品アセット情報
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        image_url:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
      required:
        - id
        - name
        - url
        - image_url
        - author
        - created_at
        - updated_at
        - deleted_at
    Creator:
      title: Creator
      type: object
      description: クリエイター情報
      properties:
        id:
          type: integer
        name:
          type: string
        thumb_image_url:
          type: string
      required:
        - id
        - name
        - thumb_image_url
    Social:
      title: Social
      type: object
      description: ユーザーSNS情報
      properties:
        id:
          type: string
        twitter_id:
          type: string
        youtube_url:
          type: string
        instagram_url:
          type: string
        facebook_url:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
      required:
        - id
        - created_at
        - updated_at
        - deleted_at
    Author:
      title: Author
      type: object
      description: 登録者情報
      properties:
        id:
          type: integer
        name:
          type: string
        thumb_image_url:
          type: string
      required:
        - id
        - name
        - thumb_image_url
  parameters: {}
  examples: {}
  responses: {}
